# Запуск дипломного проекта MAPIP (API + БД)
version: '3.8'

services:
  webapi:
    build: ./MapApi
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=12345;Database=map
    ports:
      - "5000:80"
    networks:
      - backend

  flask:
    build: ./FlaskApi
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/map
    expose:
      - "5001"
    networks:
      - backend

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: map
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data:
