worker_processes auto;
events { worker_connections 1024; }
http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  upstream mapip_core {
    server mapip-core:8000;
  }
  upstream mapip_routing {
    server mapip-routing:8080;
  }
  upstream flask_svc {
    server flask:5001;
  }

  server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /routing/ {
      proxy_pass http://mapip_routing/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
      proxy_pass http://mapip_core;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Cookie $http_cookie;
    }

    location = /GetSocialMapObject {
      proxy_pass http://mapip_core;
      proxy_set_header Host $host;
      proxy_set_header Cookie $http_cookie;
    }

    location /comments/ {
      proxy_pass http://flask_svc;
      proxy_set_header Host $host;
    }

    location /recommendations/ {
      proxy_pass http://flask_svc;
      proxy_set_header Host $host;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
